# Generated by Django 2.2.6 on 2020-10-28 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDirectory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=255, null=True)),
                ('position', models.CharField(default='NA', max_length=255, null=True)),
                ('extension', models.CharField(default='NA', max_length=50, null=True)),
                ('email', models.CharField(default='NA', max_length=255, null=True)),
                ('department', models.CharField(choices=[('PPP', 'Pejabat Pengarah Planetarium Negara'), ('UPA', 'Unit Perhubungan Awam'), ('SPD', 'Seksyen Pendidikan'), ('UTK', 'Unit Teknikal'), ('SPK', 'Seksyen Perkhidmatan'), ('UKW', 'Unit Kewangan'), ('UTM', 'Unit Teknologi Maklumat'), ('UPF', 'Unit Pengurusan Fasiliti'), ('UPT', 'Unit Pentadbiran'), ('NAV', 'Not Available')], default='NAV', max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
