# Generated by Django 2.2.6 on 2020-11-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedirectories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedirectory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
