# Generated by Django 2.2.6 on 2020-11-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedirectories', '0002_employeedirectory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedirectory',
            name='department',
            field=models.CharField(choices=[('PPP', 'Pejabat Pengarah Planetarium Negara'), ('UPA', 'Unit Perhubungan Awam'), ('SPP', 'Seksyen Pendidikan - Pameran'), ('SPC', 'Seksyen Pendidikan - Pencerapan'), ('SPB', 'Seksyen Pendidikan - Pembudayaan'), ('UTK', 'Unit Teknikal'), ('SPK', 'Seksyen Perkhidmatan'), ('UKW', 'Unit Kewangan'), ('UTM', 'Unit Teknologi Maklumat'), ('UPF', 'Unit Pengurusan Fasiliti'), ('UPT', 'Unit Pentadbiran'), ('NAV', 'Not Available')], default='NAV', max_length=3),
        ),
    ]
