# Generated by Django 2.2.6 on 2020-11-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeedirectories', '0003_auto_20201116_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedirectory',
            options={'ordering': ['-created_date']},
        ),
    ]
