# Generated by Django 2.2.6 on 2020-11-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeedirectories', '0004_auto_20201119_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedirectory',
            options={'ordering': ['created_date']},
        ),
    ]
