# Generated by Django 2.2.6 on 2021-09-02 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employeedirectories', '0005_auto_20201120_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmployeeDirectory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.CharField(default='NA', max_length=255, null=True)),
                ('position', models.CharField(default='NA', max_length=255, null=True)),
                ('extension', models.CharField(default='NA', max_length=50, null=True)),
                ('email', models.CharField(default='NA', max_length=255, null=True)),
                ('department', models.CharField(choices=[('PPP', 'Pejabat Pengarah Planetarium Negara'), ('UPA', 'Unit Perhubungan Awam'), ('SPP', 'Seksyen Pendidikan - Pameran'), ('SPC', 'Seksyen Pendidikan - Pencerapan'), ('SPB', 'Seksyen Pendidikan - Pembudayaan'), ('UTK', 'Unit Teknikal'), ('SPK', 'Seksyen Perkhidmatan'), ('UKW', 'Unit Kewangan'), ('UTM', 'Unit Teknologi Maklumat'), ('UPF', 'Unit Pengurusan Fasiliti'), ('UPT', 'Unit Pentadbiran'), ('NAV', 'Not Available')], default='NAV', max_length=3)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee directory',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
