# Generated by Django 2.2.6 on 2021-01-11 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FpxTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fpx_msgType', models.CharField(blank=True, max_length=2)),
                ('fpx_msgToken', models.CharField(blank=True, max_length=2)),
                ('fpx_fpxTxnId', models.CharField(blank=True, max_length=16)),
                ('fpx_sellerExId', models.CharField(blank=True, max_length=10)),
                ('fpx_sellerExOrderNo', models.CharField(blank=True, max_length=40)),
                ('fpx_fpxTxnTime', models.DateTimeField()),
                ('fpx_sellerTxnTime', models.DateTimeField()),
                ('fpx_sellerOrderNo', models.CharField(blank=True, max_length=40)),
                ('fpx_sellerId', models.CharField(blank=True, max_length=10)),
                ('fpx_sellerBankCode', models.CharField(blank=True, max_length=2)),
                ('fpx_txnCurrency', models.CharField(blank=True, max_length=3)),
                ('fpx_txnAmount', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('fpx_buyerEmail', models.CharField(blank=True, max_length=50)),
                ('fpx_checkSum', models.TextField(blank=True)),
                ('fpx_buyerName', models.CharField(blank=True, max_length=40)),
                ('fpx_buyerBankId', models.CharField(blank=True, max_length=10)),
                ('fpx_buyerBankBranch', models.CharField(blank=True, max_length=10)),
                ('fpx_buyerAccNo', models.CharField(blank=True, max_length=20)),
                ('fpx_buyerId', models.CharField(blank=True, max_length=20)),
                ('fpx_makerName', models.CharField(blank=True, max_length=40)),
                ('fpx_buyerIban', models.CharField(blank=True, max_length=35)),
                ('fpx_debitAuthCode', models.CharField(blank=True, max_length=2)),
                ('fpx_debitAuthNo', models.CharField(blank=True, max_length=10)),
                ('fpx_creditAuthCode', models.CharField(blank=True, max_length=2)),
                ('fpx_creditAuthNo', models.CharField(blank=True, max_length=10)),
                ('fpx_xtrainfo', models.CharField(blank=True, max_length=6)),
                ('fpx_productDesc', models.CharField(blank=True, max_length=30)),
                ('fpx_version', models.CharField(blank=True, default='7.0', max_length=3)),
                ('fpx_eaccountNum', models.CharField(blank=True, max_length=40)),
                ('fpx_ebuyerId', models.CharField(blank=True, max_length=40)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
