# Generated by Django 2.2.6 on 2021-01-13 04:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fpxtransactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bank_id', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_display_name', models.CharField(blank=True, max_length=255)),
                ('bank_active', models.CharField(blank=True, max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
