# Generated by Django 2.2.6 on 2021-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpxtransactions', '0002_banklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpxtransaction',
            name='fpx_fpxTxnTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fpxtransaction',
            name='fpx_sellerTxnTime',
            field=models.DateTimeField(null=True),
        ),
    ]
