# Generated by Django 2.2.6 on 2021-01-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpxtransactions', '0003_auto_20210113_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpxtransaction',
            name='fpx_fpxTxnTime',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='fpxtransaction',
            name='fpx_sellerTxnTime',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
