# Generated by Django 2.2.6 on 2021-01-29 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fpxtransactions', '0004_auto_20210113_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('response_code', models.CharField(blank=True, max_length=2)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
