# Generated by Django 2.2.6 on 2021-09-02 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fpxtransactions', '0005_responsecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalResponseCode',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('response_code', models.CharField(blank=True, max_length=2)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical response code',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFpxTransaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('fpx_msgType', models.CharField(blank=True, max_length=2)),
                ('fpx_msgToken', models.CharField(blank=True, max_length=2)),
                ('fpx_fpxTxnId', models.CharField(blank=True, max_length=16)),
                ('fpx_sellerExId', models.CharField(blank=True, max_length=10)),
                ('fpx_sellerExOrderNo', models.CharField(blank=True, max_length=40)),
                ('fpx_fpxTxnTime', models.CharField(blank=True, max_length=14)),
                ('fpx_sellerTxnTime', models.CharField(blank=True, max_length=14)),
                ('fpx_sellerOrderNo', models.CharField(blank=True, max_length=40)),
                ('fpx_sellerId', models.CharField(blank=True, max_length=10)),
                ('fpx_sellerBankCode', models.CharField(blank=True, max_length=2)),
                ('fpx_txnCurrency', models.CharField(blank=True, max_length=3)),
                ('fpx_txnAmount', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('fpx_buyerEmail', models.CharField(blank=True, max_length=50)),
                ('fpx_checkSum', models.TextField(blank=True)),
                ('fpx_buyerName', models.CharField(blank=True, max_length=40)),
                ('fpx_buyerBankId', models.CharField(blank=True, max_length=10)),
                ('fpx_buyerBankBranch', models.CharField(blank=True, max_length=10)),
                ('fpx_buyerAccNo', models.CharField(blank=True, max_length=20)),
                ('fpx_buyerId', models.CharField(blank=True, max_length=20)),
                ('fpx_makerName', models.CharField(blank=True, max_length=40)),
                ('fpx_buyerIban', models.CharField(blank=True, max_length=35)),
                ('fpx_debitAuthCode', models.CharField(blank=True, max_length=2)),
                ('fpx_debitAuthNo', models.CharField(blank=True, max_length=10)),
                ('fpx_creditAuthCode', models.CharField(blank=True, max_length=2)),
                ('fpx_creditAuthNo', models.CharField(blank=True, max_length=10)),
                ('fpx_xtrainfo', models.CharField(blank=True, max_length=6)),
                ('fpx_productDesc', models.CharField(blank=True, max_length=30)),
                ('fpx_version', models.CharField(blank=True, default='7.0', max_length=3)),
                ('fpx_eaccountNum', models.CharField(blank=True, max_length=40)),
                ('fpx_ebuyerId', models.CharField(blank=True, max_length=40)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fpx transaction',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBankList',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('bank_id', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_display_name', models.CharField(blank=True, max_length=255)),
                ('bank_active', models.CharField(blank=True, max_length=1)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bank list',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
