# Generated by Django 2.2.6 on 2020-09-30 05:56

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0003_auto_20200930_0254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorRide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('simulator-ride'))),
                ('title', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorRideTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.TimeField(null=True)),
                ('day', models.CharField(choices=[('MON', 'Isnin'), ('TUE', 'Selasa'), ('WED', 'Rabu'), ('THU', 'Khamis'), ('FRI', 'Jumaat'), ('SAT', 'Sabtu'), ('SUN', 'Ahad')], default='MON', max_length=3)),
                ('round', models.CharField(choices=[('P1', 'Pusingan 1'), ('P2', 'Pusingan 2'), ('P3', 'Pusingan 3'), ('P4', 'Pusingan 4'), ('P5', 'Pusingan 5')], default='P1', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulator_ride_time_venue_id', to='venues.Venue')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorRideBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('CZ', 'Citizen'), ('NC', 'Non-citizen')], default='CZ', max_length=2)),
                ('ticket_category', models.CharField(choices=[('AD', 'Adult'), ('KD', 'Kid')], default='AD', max_length=2)),
                ('ticket_quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('simulator_ride_time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulator_ride_booking_ride_time_id', to='simulatorrides.SimulatorRideTime')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulator_ride_booking_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ticket_type'],
            },
        ),
    ]
