# Generated by Django 2.2.6 on 2020-10-18 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatorridebooking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
