# Generated by Django 2.2.6 on 2020-11-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0002_simulatorridebooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatorridebooking',
            name='status',
            field=models.CharField(choices=[('SRB01', 'Accepted'), ('SRB02', 'Pending Payment'), ('SRB03', 'Payment Accepted'), ('SRB04', 'Payment Rejected'), ('SRB05', 'Refund')], default='SRB01', max_length=5),
        ),
    ]
