# Generated by Django 2.2.6 on 2020-11-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0003_simulatorridebooking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulatorridetime',
            options={'ordering': ['time']},
        ),
    ]
