# Generated by Django 2.2.6 on 2021-01-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0005_simulatorridebooking_fpx_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulatorridebooking',
            name='fpx_transaction_id',
        ),
    ]
