# Generated by Django 2.2.6 on 2021-05-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0006_remove_simulatorridebooking_fpx_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulatorridebooking',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='simulatorridebooking',
            name='ticket_free',
            field=models.BooleanField(default=False),
        ),
    ]
