# Generated by Django 2.2 on 2021-08-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0007_auto_20210518_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulatorridetime',
            options={'ordering': ['round']},
        ),
        migrations.AddField(
            model_name='simulatorridetime',
            name='simulator_time_status',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Sedang Ditayang', 'Sedang Ditayang'), ('Tunda', 'Tunda'), ('Batal', 'Batal')], default='Ada', max_length=40),
        ),
    ]
