# Generated by Django 2.2 on 2021-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0008_auto_20210813_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatorridetime',
            name='simulator_time_status',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Sedang Ditayang', 'Sedang Ditayang'), ('Tunda', 'Tunda'), ('Batal', 'Batal'), ('Telah Ditayang', 'Telah Ditayang')], default='Ada', max_length=40),
        ),
    ]
