# Generated by Django 2.2 on 2021-08-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0009_auto_20210813_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatorridetime',
            name='simulator_time_status',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Sedang Berlangsung', 'Sedang Berlangsung'), ('Berbaki 1 Kerusi', 'Berbaki 1 Kerusi'), ('Penuh', 'Penuh'), ('Batal', 'Batal'), ('Tamat', 'Tamat')], default='Ada', max_length=40),
        ),
    ]
