# Generated by Django 2.2.6 on 2021-09-02 02:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0025_auto_20210504_0529'),
        ('simulatorrides', '0010_auto_20210831_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSimulatorRideTime',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('time', models.TimeField(null=True)),
                ('day', models.CharField(choices=[('MON', 'Isnin'), ('TUE', 'Selasa'), ('WED', 'Rabu'), ('THU', 'Khamis'), ('FRI', 'Jumaat'), ('SAT', 'Sabtu'), ('SUN', 'Ahad')], default='MON', max_length=3)),
                ('round', models.CharField(choices=[('P1', 'Pusingan 1'), ('P2', 'Pusingan 2'), ('P3', 'Pusingan 3'), ('P4', 'Pusingan 4'), ('P5', 'Pusingan 5')], default='P1', max_length=2)),
                ('simulator_time_status', models.CharField(choices=[('Ada', 'Ada'), ('Sedang Berlangsung', 'Sedang Berlangsung'), ('Berbaki 1 Kerusi', 'Berbaki 1 Kerusi'), ('Penuh', 'Penuh'), ('Batal', 'Batal'), ('Tamat', 'Tamat')], default='Ada', max_length=40)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('venue_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='venues.Venue')),
            ],
            options={
                'verbose_name': 'historical simulator ride time',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSimulatorRideBooking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('booking_date', models.DateField(default=datetime.date.today)),
                ('ticket_type', models.CharField(choices=[('CZ', 'Citizen'), ('NC', 'Non-citizen')], default='CZ', max_length=2)),
                ('ticket_category', models.CharField(choices=[('AD', 'Adult'), ('KD', 'Kid')], default='AD', max_length=2)),
                ('ticket_quantity', models.IntegerField(default=0)),
                ('ticket_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('SRB01', 'Accepted'), ('SRB02', 'Pending Payment'), ('SRB03', 'Payment Accepted'), ('SRB04', 'Payment Rejected'), ('SRB05', 'Refund')], default='SRB01', max_length=5)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('simulator_ride_time_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='simulatorrides.SimulatorRideTime')),
                ('user_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical simulator ride booking',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSimulatorRide',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('image_link', models.TextField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical simulator ride',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
