# Generated by Django 2.2 on 2021-10-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0011_historicalsimulatorride_historicalsimulatorridebooking_historicalsimulatorridetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsimulatorridebooking',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='simulatorridebooking',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
