# Generated by Django 2.2 on 2021-10-16 08:12

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0012_auto_20211011_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorRideTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_link', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('simulator_ticket'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
