# Generated by Django 2.2 on 2021-10-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0013_simulatorrideticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatorrideticket',
            name='ticket_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
