# Generated by Django 2.2 on 2021-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorrides', '0014_auto_20211016_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatorrideticket',
            name='ticket_booking_id',
            field=models.CharField(default='AD', max_length=20),
        ),
    ]
