# Generated by Django 2.2.6 on 2020-11-07 16:00

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0027_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='NA', max_length=255)),
                ('description', models.CharField(blank=True, default='NA', max_length=255)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('image'))),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('program_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_program_id', to='events.EducationalProgram')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
