# Generated by Django 2.2.6 on 2021-09-02 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_historicaleducationalprogram_historicaleducationalprogramactivity_historicaleducationalprogramapplic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBanner',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('title', models.CharField(blank=True, default='NA', max_length=255)),
                ('description', models.CharField(blank=True, default='NA', max_length=255)),
                ('image_link', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.EducationalProgram')),
            ],
            options={
                'verbose_name': 'historical banner',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
