# Generated by Django 2.2 on 2020-09-03 20:22

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=255)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('genre', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('language', models.CharField(choices=[('EN', 'English'), ('MY', 'Malay')], default='EN', max_length=2)),
                ('duration_hours', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('poster_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('poster'))),
                ('trailer_link', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('trailers'))),
                ('status', models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available')], default='AV', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ShowTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('AD', 'Adult'), ('KD', 'Kid'), ('OF', 'Old Folk'), ('SD', 'Student')], default='AD', max_length=2)),
                ('ticket_type', models.CharField(choices=[('CZ', 'Citizen'), ('NC', 'Non-citizen')], default='CZ', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(blank=True)),
                ('end_datetime', models.DateTimeField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('showing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showing', to='showings.Showing')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
