# Generated by Django 2.2 on 2020-09-03 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='venue_id',
            field=models.ManyToManyField(related_name='venue', to='venues.Venue'),
        ),
        migrations.AddField(
            model_name='showticket',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showticket',
            name='showtime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtime', to='showings.Showtime'),
        ),
    ]
