# Generated by Django 2.2.6 on 2020-09-28 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showings', '0002_auto_20200903_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showticket',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showticket_customuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShowBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('CZ', 'Citizen'), ('NC', 'Non-citizen')], default='CZ', max_length=2)),
                ('ticket_category', models.CharField(choices=[('AD', 'Adult'), ('KD', 'Kid'), ('OF', 'Old Folk'), ('SD', 'Student'), ('OK', 'OKU')], default='AD', max_length=2)),
                ('ticket_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showbooking_showing', to='showings.Showing')),
                ('showtime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showbooking_showtime', to='showings.Showtime')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
