# Generated by Django 2.2.6 on 2020-09-28 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import showings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showings', '0003_auto_20200928_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='showticket',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='showticket',
            name='no_ticket',
            field=models.CharField(blank=True, default=showings.models.increment_ticket_number, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='showticket',
            name='qrcode',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='showticket',
            name='show_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='showticket_showing', to='showings.Showing'),
        ),
        migrations.AddField(
            model_name='showticket',
            name='ticket_category',
            field=models.CharField(choices=[('AD', 'Adult'), ('KD', 'Kid'), ('OF', 'Old Folk'), ('SD', 'Student'), ('OK', 'OKU')], default='AD', max_length=2),
        ),
        migrations.AddField(
            model_name='showticket',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='showticket_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='showticket',
            name='showtime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showticket_showtime', to='showings.Showtime'),
        ),
        migrations.AlterField(
            model_name='showticket',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
