# Generated by Django 2.2.6 on 2020-09-28 04:30

from django.db import migrations, models
import showings.models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0005_remove_showticket_no_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='showticket',
            name='no_ticket',
            field=models.CharField(blank=True, default=showings.models.increment_ticket_number, max_length=500, null=True),
        ),
    ]
