# Generated by Django 2.2.6 on 2020-09-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0006_showticket_no_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showticket',
            name='no_ticket',
            field=models.CharField(blank=True, default='P0000001', max_length=500, null=True),
        ),
    ]
