# Generated by Django 2.2.6 on 2020-09-28 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0009_auto_20200928_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='show_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='show_time',
            field=models.TimeField(),
        ),
    ]
