# Generated by Django 2.2.6 on 2020-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0010_auto_20200928_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='show_time',
            field=models.TimeField(null=True),
        ),
    ]
