# Generated by Django 2.2.6 on 2020-10-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0011_auto_20200928_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='showticket',
            name='ticket_seat',
            field=models.CharField(default='NA', max_length=3),
        ),
    ]
