# Generated by Django 2.2.6 on 2020-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0012_showticket_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='trailer_link',
            field=models.URLField(null=True),
        ),
    ]
