# Generated by Django 2.2.6 on 2020-11-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0013_auto_20201024_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='showbooking',
            name='ticket_seat',
            field=models.CharField(default='NA', max_length=3),
        ),
    ]
