# Generated by Django 2.2.6 on 2020-11-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0014_showbooking_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='showbooking',
            name='status',
            field=models.CharField(choices=[('SB01', 'In Progress'), ('SB02', 'Approved'), ('SB03', 'Rejected'), ('SB04', 'Pending Payment'), ('SB05', 'Payment Accepted'), ('SB06', 'Payment Rejected'), ('SB07', 'Refund')], default='SB01', max_length=4),
        ),
    ]
