# Generated by Django 2.2.6 on 2020-11-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0015_showbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
