# Generated by Django 2.2.6 on 2020-11-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0016_auto_20201124_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtime',
            options={'ordering': ['show_date']},
        ),
    ]
