# Generated by Django 2.2.6 on 2020-12-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0017_auto_20201126_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showing',
            options={'ordering': ['title_ms']},
        ),
        migrations.RenameField(
            model_name='showing',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='showing',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='showing',
            name='description_ms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='showing',
            name='title_ms',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
