# Generated by Django 2.2.6 on 2021-01-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpxtransactions', '0004_auto_20210113_0744'),
        ('showings', '0018_auto_20201218_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='showbooking',
            name='fpx_transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show_booking_fpx_transaction_id', to='fpxtransactions.FpxTransaction'),
        ),
    ]
