# Generated by Django 2.2.6 on 2021-03-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0020_remove_showbooking_fpx_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='showbooking',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
