# Generated by Django 2.2.6 on 2021-05-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0021_showbooking_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='showticket',
            name='ticket_free',
            field=models.BooleanField(default=False),
        ),
    ]
