# Generated by Django 2.2.6 on 2021-05-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0022_showticket_ticket_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='showbooking',
            name='ticket_free',
            field=models.BooleanField(default=False),
        ),
    ]
