# Generated by Django 2.2.6 on 2021-07-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0023_showbooking_ticket_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showbooking',
            name='status',
            field=models.CharField(choices=[('SB01', 'In Progress'), ('SB02', 'Approved'), ('SB03', 'Rejected'), ('SB04', 'Pending Payment'), ('SB05', 'Payment Accepted'), ('SB06', 'Payment Rejected'), ('SB07', 'Refund'), ('SB08', 'QR validate')], default='SB01', max_length=4),
        ),
    ]
