# Generated by Django 2.2 on 2021-08-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0024_auto_20210701_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='showticket',
            name='available_ticket',
            field=models.IntegerField(default=100),
        ),
    ]
