# Generated by Django 2.2 on 2021-08-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0025_showticket_available_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showticket',
            name='available_ticket',
        ),
        migrations.AddField(
            model_name='showtime',
            name='available_ticket',
            field=models.IntegerField(default=100),
        ),
    ]
