# Generated by Django 2.2 on 2021-08-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0026_auto_20210812_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='show_time_status',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Sedang Ditayang', 'Sedang Ditayang'), ('Tunda', 'Tunda'), ('Batal', 'Batal')], default='Ada', max_length=40),
        ),
    ]
