# Generated by Django 2.2 on 2021-08-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0028_auto_20210813_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='available_ticket',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='show_time_status',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Sedang Ditayang', 'Sedang Ditayang'), ('Bakal Ditayang', 'Bakal Ditayang'), ('Tunda', 'Tunda'), ('Batal', 'Batal'), ('Penuh', 'Penuh')], default='Ada', max_length=40),
        ),
    ]
