# Generated by Django 2.2.6 on 2021-09-02 02:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import showings.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showings', '0029_auto_20210831_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalShowtime',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('show_date', models.DateField(default=datetime.date.today)),
                ('show_time', models.TimeField(null=True)),
                ('show_time_status', models.CharField(choices=[('Ada', 'Ada'), ('Sedang Ditayang', 'Sedang Ditayang'), ('Bakal Ditayang', 'Bakal Ditayang'), ('Tunda', 'Tunda'), ('Batal', 'Batal'), ('Penuh', 'Penuh')], default='Ada', max_length=40)),
                ('available_ticket', models.IntegerField(default=200)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('showing_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='showings.Showing')),
            ],
            options={
                'verbose_name': 'historical showtime',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShowTicket',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('no_ticket', models.CharField(blank=True, default=showings.models.increment_ticket_number, max_length=500, null=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_category', models.CharField(choices=[('AD', 'Adult'), ('KD', 'Kid'), ('OF', 'Old Folk'), ('SD', 'Student'), ('OK', 'OKU')], default='AD', max_length=2)),
                ('ticket_type', models.CharField(choices=[('CZ', 'Citizen'), ('NC', 'Non-citizen')], default='CZ', max_length=2)),
                ('ticket_seat', models.CharField(default='NA', max_length=3)),
                ('ticket_free', models.BooleanField(default=False)),
                ('qrcode', models.CharField(default='NA', max_length=100)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('show_id', models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='showings.Showing')),
                ('showtime_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='showings.Showtime')),
                ('user_id', models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical show ticket',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShowing',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('title_en', models.CharField(default='NA', max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('title_ms', models.CharField(default='NA', max_length=255)),
                ('description_ms', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('language', models.CharField(choices=[('EN', 'English'), ('MY', 'Malay')], default='EN', max_length=2)),
                ('duration_hours', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('poster_link', models.TextField(blank=True, max_length=100, null=True)),
                ('trailer_link', models.URLField(null=True)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available')], default='AV', max_length=2)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical showing',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShowBooking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('ticket_type', models.CharField(choices=[('CZ', 'Citizen'), ('NC', 'Non-citizen')], default='CZ', max_length=2)),
                ('ticket_category', models.CharField(choices=[('AD', 'Adult'), ('KD', 'Kid'), ('OF', 'Old Folk'), ('SD', 'Student'), ('OK', 'OKU')], default='AD', max_length=2)),
                ('ticket_quantity', models.IntegerField()),
                ('ticket_seat', models.CharField(default='NA', max_length=3)),
                ('ticket_number', models.CharField(blank=True, max_length=7)),
                ('ticket_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('SB01', 'In Progress'), ('SB02', 'Approved'), ('SB03', 'Rejected'), ('SB04', 'Pending Payment'), ('SB05', 'Payment Accepted'), ('SB06', 'Payment Rejected'), ('SB07', 'Refund'), ('SB08', 'QR validate')], default='SB01', max_length=4)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('show_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='showings.Showing')),
                ('showtime_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='showings.Showtime')),
                ('user_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical show booking',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
