# Generated by Django 2.2.6 on 2021-09-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0030_historicalshowbooking_historicalshowing_historicalshowticket_historicalshowtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshowtime',
            name='show_time_status',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Sedang Ditayang', 'Sedang Ditayang'), ('Bakal Ditayang', 'Bakal Ditayang'), ('Tunda', 'Tunda'), ('Batal', 'Batal'), ('Penuh', 'Penuh'), ('Tamat', 'Tamat')], default='Ada', max_length=40),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='show_time_status',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Sedang Ditayang', 'Sedang Ditayang'), ('Bakal Ditayang', 'Bakal Ditayang'), ('Tunda', 'Tunda'), ('Batal', 'Batal'), ('Penuh', 'Penuh'), ('Tamat', 'Tamat')], default='Ada', max_length=40),
        ),
    ]
