# Generated by Django 2.2 on 2020-09-03 20:22

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('author_name', models.CharField(default='NA', max_length=100)),
                ('publisher_name', models.CharField(default='NA', max_length=100)),
                ('published_date', models.DateTimeField(null=True)),
                ('poster_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('poster'))),
                ('pdf_link', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('publication'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
