# Generated by Django 2.2.6 on 2020-09-29 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='description',
            new_name='abstract',
        ),
        migrations.AddField(
            model_name='publication',
            name='edition',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
