# Generated by Django 2.2.6 on 2020-10-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20201027_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationcategory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
