# Generated by Django 2.2.6 on 2020-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20201029_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='call_number',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='editor_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='publication',
            name='issn',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
