# Generated by Django 2.2.6 on 2020-11-24 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20201111_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author_name',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='edition',
            field=models.CharField(blank=True, default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='editor_name',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher_name',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
