# Generated by Django 2.2.6 on 2021-01-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20201124_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationcategory',
            options={'ordering': ['name_ms']},
        ),
        migrations.RenameField(
            model_name='publicationcategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='publicationcategory',
            name='name_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
    ]
