# Generated by Django 2.2.6 on 2021-01-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20210131_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['title_ms']},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='abstract',
            new_name='abstract_en',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ms',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
