# Generated by Django 2.2.6 on 2021-03-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20210131_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='download_pdf_counter',
            field=models.IntegerField(default=0),
        ),
    ]
