# Generated by Django 2.2.6 on 2021-03-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_publication_download_pdf_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', 'title_ms']},
        ),
    ]
