# Generated by Django 2.2.6 on 2021-09-02 04:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0010_auto_20210310_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPublicationCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name_en', models.CharField(blank=True, default='NA', max_length=255)),
                ('name_ms', models.CharField(blank=True, default='NA', max_length=255)),
                ('icon', models.CharField(blank=True, default='NA', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical publication category',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPublication',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('title_en', models.CharField(blank=True, default='NA', max_length=100)),
                ('title_ms', models.CharField(blank=True, default='NA', max_length=100)),
                ('description_en', models.TextField(blank=True)),
                ('description_ms', models.TextField(blank=True)),
                ('call_number', models.CharField(blank=True, default='NA', max_length=100)),
                ('abstract_en', models.CharField(blank=True, default='NA', max_length=255)),
                ('abstract_ms', models.CharField(blank=True, default='NA', max_length=255)),
                ('author_name', models.CharField(blank=True, default='NA', max_length=100)),
                ('editor_name', models.CharField(blank=True, default='NA', max_length=100)),
                ('publisher_name', models.CharField(blank=True, default='NA', max_length=100)),
                ('published_date', models.DateField(default=datetime.date.today, null=True)),
                ('isbn', models.CharField(blank=True, default='NA', max_length=100)),
                ('issn', models.CharField(blank=True, default='NA', max_length=100)),
                ('year', models.IntegerField(default=2020)),
                ('edition', models.CharField(blank=True, default='NA', max_length=20)),
                ('poster_link', models.TextField(blank=True, max_length=100, null=True)),
                ('pdf_link', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('download_pdf_counter', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('publication_category_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publications.PublicationCategory')),
            ],
            options={
                'verbose_name': 'historical publication',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
