apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: pln-eportal-webapp
  name: pln-eportal-webapp
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: pln-eportal-webapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pln-eportal-webapp
    spec:
      containers:
      - image: syafiqpipe/pln-eportal-webapp:1.0.0
        imagePullPolicy: Always   
        name: pln-eportal-webapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30