# Generated by Django 2.2.6 on 2020-11-05 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=255, null=True)),
                ('link', models.CharField(blank=True, default='NA', max_length=255)),
                ('category', models.CharField(choices=[('PTMY', 'Planetarium Malaysia'), ('PTLN', 'Planetarium Luar Negara'), ('BCMY', 'Balai Cerap Malaysia'), ('BCLN', 'Balai Cerap Luar Negara'), ('NOAV', 'Not Available')], default='NOAV', max_length=4)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
