# Generated by Django 2.2.6 on 2020-11-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklinks', '0002_auto_20201111_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicklinkcategory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='quicklinkcategory',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
