# Generated by Django 2.2.6 on 2020-12-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklinks', '0003_auto_20201120_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicklink',
            options={'ordering': ['name_ms']},
        ),
        migrations.RenameField(
            model_name='quicklink',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='quicklinkcategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='quicklink',
            name='name_ms',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quicklinkcategory',
            name='name_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
    ]
