# Generated by Django 2.2 on 2020-09-03 20:22

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=255)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('asset_type', models.CharField(choices=[('OT', 'Other')], default='OT', max_length=2)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('asset'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'asset_type'],
            },
        ),
    ]
