# Generated by Django 2.2.6 on 2021-07-08 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_amount', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('order_creation_time', models.DateTimeField(null=True)),
                ('order_currency', models.CharField(default='MYR', max_length=3)),
                ('order_id', models.CharField(blank=True, max_length=40)),
                ('order_lastupdated_time', models.DateTimeField(null=True)),
                ('order_totalauthorized_amount', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('order_totalcaptured_amount', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('order_totalrefunded_amount', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('session_id', models.CharField(blank=True, max_length=35)),
                ('sourceoffunds_type', models.CharField(default='CARD', max_length=255)),
                ('sourceoffunds_provided_card_number', models.CharField(max_length=19, null=True)),
                ('sourceoffunds_provided_card_expiry_month', models.CharField(max_length=2, null=True)),
                ('sourceoffunds_provided_card_expiry_year', models.CharField(max_length=2, null=True)),
                ('sourceoffunds_provided_card_securitycode', models.CharField(max_length=4, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('transaction_currency', models.CharField(default='MYR', max_length=3)),
                ('transaction_id', models.CharField(blank=True, max_length=40)),
                ('transaction_type', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
