# Generated by Django 2.2.6 on 2020-11-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='code',
            field=models.CharField(choices=[('EMEL01', 'Template Maklum Balas Diterima'), ('EMEL02', 'Template Maklum Balas Dijawab'), ('EMEL99', 'Tiada')], default='EMEL99', max_length=6),
        ),
    ]
