# Generated by Django 2.2.6 on 2020-11-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplates', '0003_auto_20201124_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='code',
            field=models.CharField(choices=[('EMEL01', 'Templat Maklum Balas - Diterima'), ('EMEL02', 'Templat Maklum Balas - Dijawab'), ('EMEL03', 'Templat Fasiliti - Tempahan Diproses'), ('EMEL04', 'Templat Fasiliti - Tempahan Diterima'), ('EMEL05', 'Templat Fasiliti - Tempahan Ditolak'), ('EMEL06', 'Templat Program - Tempahan Diproses'), ('EMEL07', 'Templat Program - Tempahan Diterima'), ('EMEL08', 'Templat Program - Tempahan Ditolak'), ('EMEL09', 'Templat Lawatan - Tempahan Diproses'), ('EMEL10', 'Templat Lawatan - Tempahan Diterima'), ('EMEL11', 'Templat Lawatan - Tempahan Ditolak'), ('EMEL99', 'Tiada')], default='EMEL99', max_length=6, unique=True),
        ),
    ]
