# Generated by Django 2.2.6 on 2021-09-02 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailtemplates', '0005_auto_20210218_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmailTemplate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.CharField(blank=True, default='NA', max_length=255)),
                ('code', models.CharField(choices=[('EMEL01', 'Templat Maklum Balas - Diterima'), ('EMEL02', 'Templat Maklum Balas - Dijawab'), ('EMEL03', 'Templat Fasiliti - Tempahan Diproses'), ('EMEL04', 'Templat Fasiliti - Tempahan Diterima'), ('EMEL05', 'Templat Fasiliti - Tempahan Ditolak'), ('EMEL06', 'Templat Program - Tempahan Diproses'), ('EMEL07', 'Templat Program - Tempahan Diterima'), ('EMEL08', 'Templat Program - Tempahan Ditolak'), ('EMEL09', 'Templat Lawatan - Tempahan Diproses'), ('EMEL10', 'Templat Lawatan - Tempahan Diterima'), ('EMEL11', 'Templat Lawatan - Tempahan Ditolak'), ('EMEL12', 'Templat Fasiliti - Proses Pembayaran'), ('EMEL99', 'Tiada')], db_index=True, default='EMEL99', max_length=6)),
                ('subject', models.CharField(blank=True, default='NA', max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical email template',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
