# Generated by Django 2.2.6 on 2021-02-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketprices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketprice',
            old_name='price',
            new_name='price_citizen',
        ),
        migrations.RemoveField(
            model_name='ticketprice',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='ticketprice',
            name='price_noncitizen',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
