# Generated by Django 2.2.6 on 2021-09-03 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketprices', '0002_auto_20210220_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTicketPrice',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('title_ms', models.CharField(blank=True, max_length=100)),
                ('price_citizen', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('price_noncitizen', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ticket_category', models.CharField(choices=[('AD', 'Adult'), ('KD', 'Kid'), ('OF', 'Old Folk'), ('SD', 'Student'), ('OK', 'OKU')], default='AD', max_length=2)),
                ('module', models.CharField(choices=[('simulator-ride', 'Kembara Simulasi'), ('shows', 'Tayangan')], default='simulator-ride', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ticket price',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
