# Generated by Django 2.2.6 on 2021-02-02 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicereceipts', '0004_auto_20210129_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('voucher_code', models.CharField(blank=True, max_length=10)),
                ('voucher_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('validity_until', models.DateField(null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NU', 'Not Used'), ('AU', 'Already Used'), ('EX', 'Expired')], default='NU', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('invoice_receipt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_invoice_receipt_id', to='invoicereceipts.InvoiceReceipt')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
