# Generated by Django 2.2.6 on 2021-02-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='invoice_receipt_id',
        ),
    ]
