# Generated by Django 2.2.6 on 2020-10-29 09:47

import core.helpers
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualLibraryArchiveKutubkhanah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='NA', max_length=255)),
                ('link', models.CharField(blank=True, default='NA', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='VirtualLibraryArchiveKutubkhanahCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='NA', max_length=255)),
                ('icon', models.CharField(blank=True, default='NA', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='VirtualLibraryArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='NA', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('pdf_link', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('virtuallibrary_article_pdf'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='VirtualLibraryBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='NA', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('call_number', models.CharField(blank=True, default='NA', max_length=100)),
                ('author', models.CharField(blank=True, default='NA', max_length=100)),
                ('author_added', models.CharField(blank=True, default='NA', max_length=100)),
                ('isbn', models.CharField(blank=True, default='NA', max_length=100)),
                ('issn', models.CharField(blank=True, default='NA', max_length=100)),
                ('year', models.CharField(blank=True, default='2020', max_length=4)),
                ('publisher_name', models.CharField(blank=True, default='NA', max_length=100)),
                ('published_date', models.DateField(default=datetime.date.today, null=True)),
                ('notes', models.CharField(blank=True, default='NA', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('virtuallibrary_book_image'))),
                ('pdf_link', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('virtuallibrary_book_pdf'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='VirtualLibraryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='NA', max_length=255)),
                ('icon', models.CharField(blank=True, default='NA', max_length=50)),
                ('link', models.CharField(blank=True, choices=[('tentang-kami', 'Tentang Kami'), ('artikel-terkini', 'Artikel Terkini'), ('koleksi', 'Koleksi'), ('perkhidmatan', 'Perkhidmatan'), ('not-available', 'Tiada')], default='not-available', max_length=50, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VirtualLibraryCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='NA', max_length=255)),
                ('icon', models.CharField(blank=True, default='NA', max_length=50)),
                ('link', models.CharField(blank=True, choices=[('buku', 'Buku'), ('terbitan-bersiri', 'Terbitan Bersiri'), ('e-sumber', 'eSumber'), ('arkib-kutubkhanah', 'Arkib Kutubkhanah'), ('not-available', 'Tiada')], default='not-available', max_length=50, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VirtualLibraryESource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='NA', max_length=255)),
                ('link', models.CharField(blank=True, default='NA', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='VirtualLibraryESourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='NA', max_length=255)),
                ('icon', models.CharField(blank=True, default='NA', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('virtual_library_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_library_esource_collection_id', to='virtuallibraries.VirtualLibraryCollection')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='VirtualLibrarySerialPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='NA', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('call_number', models.CharField(blank=True, default='NA', max_length=100)),
                ('author', models.CharField(blank=True, default='NA', max_length=100)),
                ('author_added', models.CharField(blank=True, default='NA', max_length=100)),
                ('isbn', models.CharField(blank=True, default='NA', max_length=100)),
                ('issn', models.CharField(blank=True, default='NA', max_length=100)),
                ('year', models.CharField(blank=True, default='2020', max_length=4)),
                ('publisher_name', models.CharField(blank=True, default='NA', max_length=100)),
                ('published_date', models.DateField(default=datetime.date.today, null=True)),
                ('notes', models.CharField(blank=True, default='NA', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('virtuallibrary_serialpublication_image'))),
                ('pdf_link', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('virtuallibrary_serialpublication_pdf'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('virtual_library_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_library_serialpublication_collection_id', to='virtuallibraries.VirtualLibraryCollection')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='Virtuallibrary',
        ),
        migrations.AddField(
            model_name='virtuallibraryesource',
            name='virtual_library_esource_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_library_esource_category_id', to='virtuallibraries.VirtualLibraryESourceCategory'),
        ),
        migrations.AddField(
            model_name='virtuallibrarybook',
            name='virtual_library_collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_library_book_collection_id', to='virtuallibraries.VirtualLibraryCollection'),
        ),
        migrations.AddField(
            model_name='virtuallibraryarticle',
            name='virtual_library_article_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_library_article_category_id', to='virtuallibraries.VirtualLibraryCategory'),
        ),
        migrations.AddField(
            model_name='virtuallibraryarchivekutubkhanahcategory',
            name='virtual_library_collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_library_archivekutubkhanah_collection_id', to='virtuallibraries.VirtualLibraryCollection'),
        ),
        migrations.AddField(
            model_name='virtuallibraryarchivekutubkhanah',
            name='virtual_library_archivekutubkhanah_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_library_archivekutubkhanah_category_id', to='virtuallibraries.VirtualLibraryArchiveKutubkhanahCategory'),
        ),
    ]
