# Generated by Django 2.2.6 on 2020-10-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibraries', '0002_auto_20201029_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtuallibraryarticle',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
