# Generated by Django 2.2.6 on 2020-10-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibraries', '0003_virtuallibraryarticle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtuallibrarycollection',
            name='virtual_library_collection_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_library_collection_category_id', to='virtuallibraries.VirtualLibraryCategory'),
        ),
    ]
