# Generated by Django 2.2.6 on 2020-11-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibraries', '0004_virtuallibrarycollection_virtual_library_collection_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtuallibrarycategory',
            name='link',
            field=models.CharField(blank=True, choices=[('tentang-kami', 'Mengenai Kami'), ('artikel-terkini', 'Artikel Terkini'), ('koleksi', 'Koleksi'), ('perkhidmatan', 'Perkhidmatan'), ('not-available', 'Tiada')], default='not-available', max_length=50, unique=True),
        ),
    ]
