# Generated by Django 2.2.6 on 2020-11-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibraries', '0005_auto_20201111_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtuallibrarybook',
            name='editor',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='virtuallibraryserialpublication',
            name='editor',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
