# Generated by Django 2.2.6 on 2020-11-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibraries', '0006_auto_20201116_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtuallibraryarchivekutubkhanahcategory',
            name='archive_from',
            field=models.CharField(choices=[('KBK', 'Koleksi - Buku'), ('KTB', 'Koleksi - Terbitan Bersiri'), ('NAV', 'Not Available')], default='NAV', max_length=3),
        ),
        migrations.AlterField(
            model_name='virtuallibrarybook',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('IAC', 'Inactive'), ('ARC', 'Archive')], default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='virtuallibraryserialpublication',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('IAC', 'Inactive'), ('ARC', 'Archive')], default='ACT', max_length=3),
        ),
    ]
