# Generated by Django 2.2.6 on 2021-02-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibraries', '0007_auto_20201120_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtuallibrarycategory',
            options={'ordering': ['name_ms']},
        ),
        migrations.AlterModelOptions(
            name='virtuallibrarycollection',
            options={'ordering': ['name_ms']},
        ),
        migrations.RenameField(
            model_name='virtuallibraryarchivekutubkhanah',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='virtuallibraryarchivekutubkhanahcategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='virtuallibraryarticle',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='virtuallibraryarticle',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='virtuallibrarybook',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='virtuallibrarybook',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='virtuallibrarycategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='virtuallibrarycollection',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='virtuallibraryesource',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='virtuallibraryesourcecategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='virtuallibraryserialpublication',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='virtuallibraryserialpublication',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='virtuallibraryarchivekutubkhanah',
            name='name_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='virtuallibraryarchivekutubkhanahcategory',
            name='name_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='virtuallibraryarticle',
            name='description_ms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='virtuallibraryarticle',
            name='name_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='virtuallibrarybook',
            name='description_ms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='virtuallibrarybook',
            name='title_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='virtuallibrarycategory',
            name='name_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='virtuallibrarycollection',
            name='name_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='virtuallibraryesource',
            name='name_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='virtuallibraryesourcecategory',
            name='name_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='virtuallibraryserialpublication',
            name='description_ms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='virtuallibraryserialpublication',
            name='title_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
    ]
