# Generated by Django 2.2.6 on 2021-03-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibraries', '0008_auto_20210208_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtuallibraryarticle',
            name='download_pdf_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtuallibrarybook',
            name='download_pdf_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtuallibraryserialpublication',
            name='download_pdf_counter',
            field=models.IntegerField(default=0),
        ),
    ]
