apiVersion: v1
kind: Service
metadata:
  name: pln-eportal-api
  labels:
    service: pln-eportal-api
spec:
  selector:
    app: pln-eportal-api
  ports:
  - port: 5000
    targetPort: 5000