# Generated by Django 2.2.6 on 2020-09-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('SA', 'Super Admin'), ('AD', 'Admin'), ('AF', 'Admin Finance'), ('AL', 'Admin Library'), ('AP', 'Admin Pameran'), ('AG', 'Admin Program'), ('AL', 'Admin Lawatan'), ('HC', 'Head Counter'), ('AM', 'Admin Maklum Balas')], default='CS', max_length=2),
        ),
    ]
