# Generated by Django 2.2.6 on 2020-10-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200923_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address',
            new_name='address_1',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
