# Generated by Django 2.2.6 on 2020-10-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201013_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='race_type',
            field=models.CharField(choices=[('CN', 'Chinese'), ('ID', 'Indian'), ('ML', 'Malay'), ('OT', 'Others'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
