# Generated by Django 2.2.6 on 2021-02-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201024_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('DR', 'Director'), ('SA', 'Super Admin'), ('FA', 'Finance Admin'), ('TA', 'Technical Admin'), ('TC', 'Ticket Counter Admin'), ('VA', 'Visit Admin'), ('EP', 'Educational Program Admin'), ('EA', 'Exhibition Admin'), ('PK', 'Publishing & Kutubkhanah Admin'), ('SV', 'Survey Admin'), ('CS', 'Customer')], default='CS', max_length=2),
        ),
    ]
