# Generated by Django 2.2.6 on 2021-01-25 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulatorrides', '0005_simulatorridebooking_fpx_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showings', '0019_showbooking_fpx_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cart_status', models.CharField(choices=[('CM', 'Completed'), ('AB', 'Abandoned'), ('CR', 'Created'), ('NA', 'Not Available')], default='CR', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('show_booking_id', models.ManyToManyField(blank=True, related_name='cart_show_booking', to='showings.ShowBooking')),
                ('simulator_ride_booking_id', models.ManyToManyField(blank=True, related_name='cart_simulator_ride_booking', to='simulatorrides.SimulatorRideBooking')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
