# Generated by Django 2.2.6 on 2021-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0023_auto_20210210_0445'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='facility_booking_id',
            field=models.ManyToManyField(blank=True, related_name='cart_facility_booking', to='venues.FacilityBooking'),
        ),
    ]
