# Generated by Django 2.2.6 on 2021-05-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_facility_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(choices=[('CM', 'Completed'), ('AB', 'Abandoned'), ('CR', 'Created'), ('PD', 'Pending'), ('NA', 'Not Available')], default='CR', max_length=2),
        ),
    ]
