# Generated by Django 2.2.6 on 2020-12-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='answer_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='question_en',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
    ]
