# Generated by Django 2.2.6 on 2021-09-02 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faqs', '0002_auto_20201215_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFaq',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('question_en', models.CharField(blank=True, default='NA', max_length=255)),
                ('answer_en', models.TextField(blank=True)),
                ('question_ms', models.CharField(blank=True, default='NA', max_length=255)),
                ('answer_ms', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical faq',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
