# Generated by Django 2.2.6 on 2021-02-03 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fpxtransactions', '0005_responsecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('refund_type', models.CharField(choices=[('T', 'Ticket'), ('M', 'Money')], default='T', max_length=1)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('acc_number', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('incharge_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RC', 'Refund Created'), ('RS', 'Refund Success'), ('RF', 'Refund Failed')], default='RC', max_length=2)),
                ('pic_verification_datetime', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('bank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_bank_id', to='fpxtransactions.BankList')),
                ('incharge_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_incharge_id', to=settings.AUTH_USER_MODEL)),
                ('pic_verification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_pic_verification_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
