# Generated by Django 2.2.6 on 2021-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('RC', 'Refund Created'), ('RA', 'Refund Approved'), ('RR', 'Refund Rejected')], default='RC', max_length=2),
        ),
    ]
