# Generated by Django 2.2.6 on 2021-02-04 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_auto_20201110_0820'),
        ('showings', '0020_remove_showbooking_fpx_transaction_id'),
        ('simulatorrides', '0006_remove_simulatorridebooking_fpx_transaction_id'),
        ('refunds', '0002_auto_20210203_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='facility_booking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_facility_booking_id', to='venues.FacilityBooking'),
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_running_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='refund',
            name='show_booking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_show_booking_id', to='showings.ShowBooking'),
        ),
        migrations.AddField(
            model_name='refund',
            name='simulator_ride_booking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_simulator_ride_booking_id', to='simulatorrides.SimulatorRideBooking'),
        ),
    ]
