# Generated by Django 2.2.6 on 2021-09-03 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fpxtransactions', '0006_historicalbanklist_historicalfpxtransaction_historicalresponsecode'),
        ('showings', '0030_historicalshowbooking_historicalshowing_historicalshowticket_historicalshowtime'),
        ('simulatorrides', '0011_historicalsimulatorride_historicalsimulatorridebooking_historicalsimulatorridetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0027_historicalvenue'),
        ('refunds', '0003_auto_20210204_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRefund',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('refund_running_no', models.CharField(blank=True, max_length=100)),
                ('refund_type', models.CharField(choices=[('T', 'Ticket'), ('M', 'Money')], default='T', max_length=1)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('acc_number', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('incharge_datetime', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('RC', 'Refund Created'), ('RA', 'Refund Approved'), ('RR', 'Refund Rejected')], default='RC', max_length=2)),
                ('pic_verification_datetime', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fpxtransactions.BankList')),
                ('facility_booking_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='venues.FacilityBooking')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incharge_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pic_verification_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('show_booking_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='showings.ShowBooking')),
                ('simulator_ride_booking_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='simulatorrides.SimulatorRideBooking')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical refund',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
