# Generated by Django 2.2.6 on 2020-10-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='questionnaire_fieldname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
