# Generated by Django 2.2.6 on 2020-10-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyquestion_questionnaire_fieldname'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='questionnaire_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='questionnaire_type',
            field=models.CharField(choices=[('CB', 'Checkbox'), ('SL', 'Selection'), ('TB', 'Textbox'), ('RB', 'Radiobox'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
