# Generated by Django 2.2.6 on 2020-11-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20201013_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='questionnaire_type',
            field=models.CharField(choices=[('CB', 'Checkbox'), ('SL', 'Selection'), ('TB', 'Textbox'), ('RB', 'Radiobox'), ('RT', 'Rating'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
