# Generated by Django 2.2.6 on 2020-11-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20201118_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='questionnaire_question',
            field=models.TextField(blank=True),
        ),
    ]
