# Generated by Django 2.2.6 on 2020-12-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20201124_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='questionnaire_module',
            field=models.CharField(choices=[('M01', 'Tayangan'), ('M02', 'Pameran'), ('M03', 'Program Pendidikan'), ('M04', 'Keberkesanan'), ('M05', 'Kembara Simulasi'), ('M06', 'Lawatan'), ('M07', 'Kutubkhanah Mini/Penerbitan'), ('M08', 'Fasiliti'), ('NAV', 'Not Available')], default='NAV', max_length=3),
        ),
    ]
