# Generated by Django 2.2.6 on 2021-01-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20201202_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='questionnaire_question',
            new_name='questionnaire_question_en',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='questionnaire_question_ms',
            field=models.TextField(blank=True),
        ),
    ]
