# Generated by Django 2.2.6 on 2021-03-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20210131_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='questionnaire_required',
            field=models.BooleanField(default=False),
        ),
    ]
