# Generated by Django 2.2.6 on 2021-02-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20201218_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description_ms',
            field=models.TextField(blank=True),
        ),
    ]
