# Generated by Django 2.2.6 on 2021-02-11 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20210208_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title_en', models.CharField(blank=True, default='NA', max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('title_ms', models.CharField(blank=True, default='NA', max_length=255)),
                ('description_ms', models.TextField(blank=True)),
                ('submodule', models.CharField(choices=[('arkib-kutubkhanah', 'Arkib Kutubkhanah'), ('buku', 'Buku'), ('e-sumber', 'eSumber'), ('terbitan-bersiri', 'Terbitan Bersiri'), ('tentang-kami', 'Mengenai Kami')], default='arkib-kutubkhanah', max_length=20, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
