# Generated by Django 2.2.6 on 2021-09-02 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0005_submodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSubModule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('title_en', models.CharField(blank=True, default='NA', max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('title_ms', models.CharField(blank=True, default='NA', max_length=255)),
                ('description_ms', models.TextField(blank=True)),
                ('submodule', models.CharField(choices=[('arkib-kutubkhanah', 'Arkib Kutubkhanah'), ('buku', 'Buku'), ('e-sumber', 'eSumber'), ('terbitan-bersiri', 'Terbitan Bersiri'), ('tentang-kami', 'Mengenai Kami')], db_index=True, default='arkib-kutubkhanah', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sub module',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalModule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('title_en', models.CharField(blank=True, default='NA', max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('title_ms', models.CharField(blank=True, default='NA', max_length=255)),
                ('description_ms', models.TextField(blank=True)),
                ('image_link', models.TextField(blank=True, max_length=100, null=True)),
                ('module', models.CharField(choices=[('simulator-ride', 'Kembara Simulasi'), ('shows', 'Tayangan'), ('exhibit', 'Pameran'), ('visit', 'Lawatan'), ('program', 'Program Pendidikan'), ('survey', 'Maklum Balas'), ('facility', 'Fasiliti'), ('publication', 'Penerbitan'), ('virtual-library', 'Kutubkhanah Mini')], db_index=True, default='simulator-ride', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical module',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
