# Generated by Django 2.2.6 on 2021-02-26 02:27

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('payment-attachment'))),
                ('amount_receive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('summary', models.TextField(blank=True, default='NA', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
