# Generated by Django 2.2.6 on 2020-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_admin',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_user',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
    ]
