# Generated by Django 2.2.6 on 2020-11-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_auto_20201105_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
