# Generated by Django 2.2.6 on 2021-02-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_feedback_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
