# Generated by Django 2.2.6 on 2021-08-12 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_feedback_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment_admin',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment_user',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
