# Generated by Django 2.2.6 on 2021-03-24 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosDailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OP', 'Counter Open'), ('CL', 'Counter Closed')], default='OP', max_length=2)),
                ('opened_timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_cash', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expected_cash_at_closing', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('transactions', models.IntegerField(default=0, null=True)),
                ('refund', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('refund_transactions', models.IntegerField(default=0, null=True)),
                ('net', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('qr', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('debit_transactions', models.IntegerField(null=True)),
                ('credit_transactions', models.IntegerField(null=True)),
                ('qr_transactions', models.IntegerField(null=True)),
                ('show_cz_adult', models.IntegerField(default=0, null=True)),
                ('show_cz_kid', models.IntegerField(default=0, null=True)),
                ('show_cz_student', models.IntegerField(default=0, null=True)),
                ('show_cz_oku', models.IntegerField(default=0, null=True)),
                ('show_cz_old_folk', models.IntegerField(default=0, null=True)),
                ('show_nz_adult', models.IntegerField(default=0, null=True)),
                ('show_nz_kid', models.IntegerField(default=0, null=True)),
                ('show_nz_student', models.IntegerField(default=0, null=True)),
                ('show_nz_oku', models.IntegerField(default=0, null=True)),
                ('show_nz_old_folk', models.IntegerField(default=0, null=True)),
                ('space_cz_adult', models.IntegerField(default=0, null=True)),
                ('space_cz_kid', models.IntegerField(default=0, null=True)),
                ('space_nz_adult', models.IntegerField(default=0, null=True)),
                ('space_nz_kid', models.IntegerField(default=0, null=True)),
                ('total_facility_paid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
