# Generated by Django 2.2.6 on 2021-01-28 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IC', 'Invoice Created'), ('PP', 'Pending Payment'), ('PS', 'Payment Successful'), ('PR', 'Payment Rejected'), ('RC', 'Receipt Created')], default='IC', max_length=2)),
                ('invoice_created_datetime', models.DateTimeField(null=True)),
                ('pending_payment_datetime', models.DateTimeField(null=True)),
                ('payment_successful_datetime', models.DateTimeField(null=True)),
                ('payment_rejected_datetime', models.DateTimeField(null=True)),
                ('receipt_created_datetime', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cart_id', models.ManyToManyField(blank=True, related_name='invoice_receipt_cart', to='carts.Cart')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
