# Generated by Django 2.2.6 on 2021-01-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpxtransactions', '0004_auto_20210113_0744'),
        ('invoicereceipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceipt',
            name='fpx_transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_receipt_fpx_transaction_id', to='fpxtransactions.FpxTransaction'),
        ),
    ]
