# Generated by Django 2.2.6 on 2021-01-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicereceipts', '0002_invoicereceipt_fpx_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceipt',
            name='total_all_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
