# Generated by Django 2.2.6 on 2021-01-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicereceipts', '0003_invoicereceipt_total_all_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceipt',
            name='invoice_running_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoicereceipt',
            name='receipt_running_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
