# Generated by Django 2.2.6 on 2021-02-03 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_remove_voucher_invoice_receipt_id'),
        ('invoicereceipts', '0004_auto_20210129_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceipt',
            name='voucher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_receipt_voucher_id', to='vouchers.Voucher'),
        ),
    ]
