# Generated by Django 2.2.6 on 2021-02-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicereceipts', '0005_invoicereceipt_voucher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicereceipt',
            old_name='total_all_price',
            new_name='total_price_after_voucher',
        ),
        migrations.AddField(
            model_name='invoicereceipt',
            name='total_price_before_voucher',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoicereceipt',
            name='total_voucher',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
