# Generated by Django 2.2.6 on 2021-02-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashtransactions', '0001_initial'),
        ('invoicereceipts', '0007_invoicereceipt_cash_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicereceipt',
            name='cash_transaction_id',
        ),
        migrations.AddField(
            model_name='invoicereceipt',
            name='cash_transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_receipt_cash_transaction_id', to='cashtransactions.CashTransaction'),
        ),
    ]
