# Generated by Django 2.2.6 on 2021-03-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicereceipts', '0008_auto_20210226_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceipt',
            name='type',
            field=models.CharField(choices=[('T', 'Tunai / Cash'), ('F', 'FPX'), ('C', 'Kad Kredit / Credit Card Portal'), ('D', 'Kad Debit / Debit Card'), ('Q', 'QR Pay'), ('K', 'Kad Kredit / Credit Card POS')], default='T', max_length=1),
        ),
    ]
