# Generated by Django 2.2 on 2021-08-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicereceipts', '0009_invoicereceipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceipt',
            name='qr_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
