# Generated by Django 2.2.6 on 2021-09-03 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fpxtransactions', '0006_historicalbanklist_historicalfpxtransaction_historicalresponsecode'),
        ('cashtransactions', '0001_initial'),
        ('vouchers', '0003_historicalvoucher'),
        ('invoicereceipts', '0010_invoicereceipt_qr_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoiceReceipt',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('total_price_before_voucher', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_voucher', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_price_after_voucher', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('IC', 'Invoice Created'), ('PP', 'Pending Payment'), ('PS', 'Payment Successful'), ('PR', 'Payment Rejected'), ('RC', 'Receipt Created')], default='IC', max_length=2)),
                ('type', models.CharField(choices=[('T', 'Tunai / Cash'), ('F', 'FPX'), ('C', 'Kad Kredit / Credit Card Portal'), ('D', 'Kad Debit / Debit Card'), ('Q', 'QR Pay'), ('K', 'Kad Kredit / Credit Card POS')], default='T', max_length=1)),
                ('invoice_created_datetime', models.DateTimeField(null=True)),
                ('pending_payment_datetime', models.DateTimeField(null=True)),
                ('payment_successful_datetime', models.DateTimeField(null=True)),
                ('payment_rejected_datetime', models.DateTimeField(null=True)),
                ('receipt_created_datetime', models.DateTimeField(null=True)),
                ('qr_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_running_no', models.CharField(blank=True, max_length=100)),
                ('receipt_running_no', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cash_transaction_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashtransactions.CashTransaction')),
                ('fpx_transaction_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fpxtransactions.FpxTransaction')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voucher_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vouchers.Voucher')),
            ],
            options={
                'verbose_name': 'historical invoice receipt',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
