# Generated by Django 2.2 on 2020-09-03 20:22

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=255)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('facility_type', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('price', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(default=0)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('facility'))),
                ('pdf_link', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('facility_pdf'))),
                ('promo_link', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('facility_promo'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('pic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_pic_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=255)),
                ('location', models.CharField(default='NA', max_length=255)),
                ('max_capacity', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=255)),
                ('start_datetime', models.DateTimeField(blank=True)),
                ('end_datetime', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('IP', 'In Process'), ('RJ', 'Rejected')], default='IP', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_app_customer_id', to=settings.AUTH_USER_MODEL)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_id', to='venues.Facility')),
                ('pic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_app_pic_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
