# Generated by Django 2.2.6 on 2020-09-30 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_pic_id'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='asset_id',
            field=models.ManyToManyField(related_name='facility_asset_id', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='facility',
            name='venue_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_venue_id', to='venues.Venue'),
        ),
    ]
