# Generated by Django 2.2.6 on 2020-09-30 02:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20200930_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitybooking',
            old_name='customer_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='facilitybooking',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='facilitybooking',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='organisation_category',
            field=models.CharField(choices=[('GV', 'Government'), ('SC', 'School'), ('UN', 'University'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='organisation_name',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='pic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_app_pic_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
