# Generated by Django 2.2.6 on 2020-10-22 02:09

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_type',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='price',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='size',
        ),
        migrations.RemoveField(
            model_name='facilitybooking',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='facility',
            name='area_size',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_category',
            field=models.CharField(choices=[('TA', 'Teater Angkasa'), ('GP', 'Galeri Pameran'), ('TT', 'Teatret'), ('BC', 'Bilik Centaurus'), ('KR', 'Kawasan Rekreasi'), ('SM', 'Stesen Mikrosatelit'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_subategory',
            field=models.CharField(choices=[('ZONE', 'Titan'), ('ZTWO', 'Milky Way'), ('ZTHR', 'Sculpture'), ('ZFOU', 'Callisto'), ('ZFIV', 'Balai Cerap Purba'), ('NA', 'Not Available')], default='NA', max_length=4),
        ),
        migrations.AddField(
            model_name='facility',
            name='have_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='booking_days',
            field=models.CharField(choices=[('HALF', 'Separuh Hari'), ('FULL', 'Satu Hari'), ('NONE', 'Tiada')], default='NONE', max_length=4),
        ),
        migrations.CreateModel(
            name='FacilityPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('facility_description', models.CharField(blank=True, default='NA', max_length=255)),
                ('facility_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('facility_days', models.CharField(choices=[('HALF', 'Separuh Hari'), ('FULL', 'Satu Hari'), ('NONE', 'Tiada')], default='NONE', max_length=4)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_price_facility_id', to='venues.Facility')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('facility_image', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('facility'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_image_facility_id', to='venues.Facility')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
