# Generated by Django 2.2.6 on 2020-10-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_auto_20201022_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
