# Generated by Django 2.2.6 on 2020-10-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_auto_20201022_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='facility_subategory',
            new_name='facility_subcategory',
        ),
    ]
