# Generated by Django 2.2.6 on 2020-10-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_auto_20201022_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityprice',
            name='facility_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
