# Generated by Django 2.2.6 on 2020-10-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_auto_20201022_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitybooking',
            name='title',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
