# Generated by Django 2.2.6 on 2020-11-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_auto_20201110_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysubcategory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
