# Generated by Django 2.2.6 on 2020-11-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_facilitysubcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_subcategory_id', to='venues.FacilitySubcategory'),
        ),
    ]
