# Generated by Django 2.2.6 on 2020-11-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_auto_20201110_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysubcategory',
            name='facility_category',
            field=models.CharField(choices=[('TA', 'Teater Angkasa'), ('GP', 'Galeri Pameran'), ('TT', 'Bilik Orion'), ('BC', 'Bilik Centaurus'), ('KR', 'Kawasan Rekreasi'), ('SM', 'Stesen Mikrosatelit'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_category',
            field=models.CharField(choices=[('TA', 'Teater Angkasa'), ('GP', 'Galeri Pameran'), ('TT', 'Bilik Orion'), ('BC', 'Bilik Centaurus'), ('KR', 'Kawasan Rekreasi'), ('SM', 'Stesen Mikrosatelit'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
