# Generated by Django 2.2.6 on 2021-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_auto_20201110_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitybooking',
            name='status',
            field=models.CharField(choices=[('FB01', 'In Progress'), ('FB02', 'Approved'), ('FB03', 'Rejected'), ('FB04', 'Pending Payment'), ('FB05', 'Payment Accepted'), ('FB06', 'Payment Rejected'), ('FB07', 'Refund')], default='FB01', max_length=2),
        ),
    ]
