# Generated by Django 2.2.6 on 2021-02-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_auto_20210204_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name_ms']},
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='equipment_description',
            new_name='description_ms',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='equipment_name',
            new_name='equipment_name_en',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='facility',
            name='equipment_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='equipment_description_ms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='equipment_name_ms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='facility',
            name='name_ms',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
