# Generated by Django 2.2.6 on 2021-02-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_auto_20210207_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityprice',
            old_name='facility_description',
            new_name='facility_description_en',
        ),
        migrations.AddField(
            model_name='facilityprice',
            name='facility_description_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
    ]
