# Generated by Django 2.2.6 on 2021-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0019_auto_20210207_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitysubcategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='facilitysubcategory',
            name='name_ms',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
