# Generated by Django 2.2.6 on 2021-02-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0020_auto_20210207_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityprice',
            old_name='facility_price',
            new_name='facility_price_full',
        ),
        migrations.RemoveField(
            model_name='facilityprice',
            name='facility_days',
        ),
        migrations.AddField(
            model_name='facilityprice',
            name='facility_price_half',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='facilityprice',
            name='facility_description_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facilityprice',
            name='facility_description_ms',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
