# Generated by Django 2.2.6 on 2021-02-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0022_facilityprice_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitybooking',
            name='want_equipment',
            field=models.CharField(choices=[('WITH', 'With Equipment'), ('WOUT', 'Without Equipment'), ('NA', 'Not Available')], default='NA', max_length=4),
        ),
    ]
