# Generated by Django 2.2.6 on 2021-03-02 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0023_auto_20210210_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitybooking',
            name='user_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='user_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='user_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_app_customer_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
