# Generated by Django 2.2.6 on 2021-05-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0024_auto_20210302_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitybooking',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='rejected_date',
            field=models.DateTimeField(null=True),
        ),
    ]
