# Generated by Django 2.2.6 on 2021-09-02 02:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0025_auto_20210504_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFacilitySubcategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('name_en', models.CharField(blank=True, max_length=50)),
                ('name_ms', models.CharField(blank=True, max_length=50)),
                ('image_link', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('facility_category', models.CharField(choices=[('TA', 'Teater Angkasa'), ('GP', 'Galeri Pameran'), ('TT', 'Bilik Orion'), ('BC', 'Bilik Centaurus'), ('KR', 'Kawasan Rekreasi'), ('SM', 'Stesen Mikrosatelit'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical facility subcategory',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFacilityPrice',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('facility_description_en', models.CharField(blank=True, max_length=255)),
                ('facility_description_ms', models.CharField(blank=True, max_length=255)),
                ('facility_price_half', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('facility_price_full', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('equipment', models.CharField(choices=[('WITH', 'With Equipment'), ('WOUT', 'Without Equipment'), ('NA', 'Not Available')], default='NA', max_length=4)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('facility_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='venues.Facility')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical facility price',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFacilityImage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('facility_image', models.TextField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('facility_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='venues.Facility')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical facility image',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFacilityBooking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('title', models.CharField(blank=True, default='NA', max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_phone', models.CharField(blank=True, max_length=100)),
                ('user_email', models.CharField(blank=True, max_length=100)),
                ('organisation_name', models.CharField(default='NA', max_length=255)),
                ('organisation_category', models.CharField(choices=[('GV', 'Government'), ('SC', 'School'), ('UN', 'University'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('booking_date', models.DateField(default=datetime.date.today)),
                ('booking_days', models.CharField(choices=[('HALF', 'Separuh Hari'), ('FULL', 'Satu Hari'), ('NONE', 'Tiada')], default='NONE', max_length=4)),
                ('number_of_people', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('want_equipment', models.CharField(choices=[('WITH', 'With Equipment'), ('WOUT', 'Without Equipment'), ('NA', 'Not Available')], default='NA', max_length=4)),
                ('approved_date', models.DateTimeField(null=True)),
                ('rejected_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('FB01', 'In Progress'), ('FB02', 'Approved'), ('FB03', 'Rejected'), ('FB04', 'Pending Payment'), ('FB05', 'Payment Accepted'), ('FB06', 'Payment Rejected'), ('FB07', 'Refund')], default='FB01', max_length=4)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('facility_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='venues.Facility')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pic_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical facility booking',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFacility',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name_en', models.CharField(default='NA', max_length=255)),
                ('name_ms', models.CharField(default='NA', max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_ms', models.TextField(blank=True)),
                ('facility_category', models.CharField(choices=[('TA', 'Teater Angkasa'), ('GP', 'Galeri Pameran'), ('TT', 'Bilik Orion'), ('BC', 'Bilik Centaurus'), ('KR', 'Kawasan Rekreasi'), ('SM', 'Stesen Mikrosatelit'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('area_size', models.CharField(blank=True, default='NA', max_length=100)),
                ('max_capacity', models.IntegerField(default=0)),
                ('have_price', models.BooleanField(default=False)),
                ('pdf_link', models.TextField(blank=True, max_length=100, null=True)),
                ('promo_link', models.TextField(blank=True, max_length=100, null=True)),
                ('equipment_name_en', models.CharField(blank=True, max_length=255)),
                ('equipment_name_ms', models.CharField(blank=True, max_length=255)),
                ('equipment_description_en', models.TextField(blank=True)),
                ('equipment_description_ms', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('facility_subcategory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='venues.FacilitySubcategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pic_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('venue_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='venues.Venue')),
            ],
            options={
                'verbose_name': 'historical facility',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
