# Generated by Django 2.2.6 on 2021-09-02 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0026_historicalfacility_historicalfacilitybooking_historicalfacilityimage_historicalfacilityprice_histori'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVenue',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.CharField(default='NA', max_length=255)),
                ('location', models.CharField(default='NA', max_length=255)),
                ('max_capacity', models.IntegerField(default=0)),
                ('zone', models.CharField(choices=[('A', 'Alam Semesta'), ('B', 'Ruang Kanak-kanak'), ('C', 'Teknologi Satelit'), ('D', 'Misi Angkasa'), ('E', 'Sistem Solar'), ('F', 'Gelombang'), ('N', 'Not Available')], default='N', max_length=1)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical venue',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
