# Generated by Django 2.2.6 on 2021-02-15 07:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloseBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_start', models.DateField(default=datetime.date.today, null=True)),
                ('date_end', models.DateField(default=datetime.date.today, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_ms', models.CharField(blank=True, max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_ms', models.TextField(blank=True)),
                ('module', models.CharField(choices=[('simulator-ride', 'Kembara Simulasi'), ('shows', 'Tayangan'), ('facility', 'Fasiliti'), ('program', 'Program Pendidikan'), ('visit', 'Lawatan')], default='simulator-ride', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
