# Generated by Django 2.2 on 2020-09-03 20:22

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=255)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('program_type', models.CharField(choices=[('PL', 'Public'), ('PV', 'Private')], default='PL', max_length=2)),
                ('min_participant', models.IntegerField(default=0)),
                ('max_participant', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('poster_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('poster'))),
                ('status', models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available')], default='AV', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EducationalProgramApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('organisation_name', models.CharField(default='NA', max_length=255)),
                ('organisation_category', models.CharField(choices=[('GV', 'Government'), ('SC', 'School'), ('UN', 'University'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('participant', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('IP', 'In process'), ('RJ', 'Rejected')], default='IP', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['organisation_name'],
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=255)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('poster_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('poster'))),
                ('status', models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available')], default='AV', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VisitApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=255)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('organisation_name', models.CharField(default='NA', max_length=255)),
                ('organisation_category', models.CharField(choices=[('GV', 'Government'), ('SC', 'School'), ('UN', 'University'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('total_participant', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('IP', 'In process'), ('RJ', 'Rejected')], default='IP', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
