# Generated by Django 2.2 on 2020-09-03 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_asset_pic_id'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitapplication',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitapplication',
            name='pic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_pic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='asset_id',
            field=models.ManyToManyField(related_name='exhibit_asset', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='pic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_pic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_venue', to='venues.Venue'),
        ),
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_program_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='educational_program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_program', to='events.EducationalProgram'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='coordinator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_program_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_program_venue', to='venues.Venue'),
        ),
    ]
