# Generated by Django 2.2.6 on 2020-09-28 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200903_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitapplication',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='visitapplication',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='visitapplication',
            name='visit_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='visitapplication',
            name='visit_time',
            field=models.TimeField(null=True),
        ),
    ]
