# Generated by Django 2.2.6 on 2020-09-28 17:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20200928_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalprogram',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='educationalprogram',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='program_category',
            field=models.CharField(choices=[('P1', 'PROGRAM PEMBANGUNAN MURID/GURU'), ('P2', 'PROGRAM PENCERAPAN'), ('P3', 'PROGRAM KHAS'), ('P4', 'PROGRAM KEBANGSAAN'), ('P5', 'PROGRAM ANTARABANGSA'), ('P6', 'PROGRAM/RAKAN KERJASAMA'), ('P7', 'PROGRAM JANGKAUAN (6 ZON)'), ('P8', 'SEMINAR, CERAMAH, PLANETARIUM TALKS'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='program_opento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='website_link',
            field=models.URLField(default='NA'),
        ),
        migrations.RemoveField(
            model_name='educationalprogram',
            name='coordinator_id',
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='coordinator_id',
            field=models.ManyToManyField(related_name='educational_program_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EducationalProgramDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('program_date', models.DateField(default=datetime.date.today)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_program_date_program_id', to='events.EducationalProgram')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
