# Generated by Django 2.2.6 on 2020-09-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        ('events', '0005_auto_20200928_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalprogram',
            name='venue_id',
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='venue_id',
            field=models.ManyToManyField(related_name='educational_program_venue', to='venues.Venue'),
        ),
    ]
