# Generated by Django 2.2.6 on 2020-09-29 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200929_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='educational_program_date_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educational_program_date', to='events.EducationalProgramDate'),
        ),
    ]
