# Generated by Django 2.2.6 on 2020-09-30 13:24

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_zone'),
        ('events', '0007_educationalprogramapplication_educational_program_date_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibit',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='poster_link',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='venue_id',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='image_link',
            field=models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('image')),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='qrcode',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='zone',
            field=models.CharField(choices=[('A', 'Alam Semesta'), ('B', 'Ruang Kanak-kanak'), ('C', 'Teknologi Satelit'), ('D', 'Misi Angkasa'), ('E', 'Sistem Solar'), ('F', 'Gelombang'), ('N', 'Not Available')], default='N', max_length=1, unique=True),
        ),
        migrations.CreateModel(
            name='ExhibitList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=255)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('image'))),
                ('status', models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available')], default='AV', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('exhibit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_list_exhibit_id', to='events.Exhibit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=255)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('image'))),
                ('video_link', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('video'))),
                ('qrcode', models.CharField(default='NA', max_length=255)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available')], default='AV', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('exhibit_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_detail_exhibit_list_id', to='events.Exhibit')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_detail_venue', to='venues.Venue')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
