# Generated by Django 2.2.6 on 2020-10-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200930_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='video_link',
            field=models.URLField(default='NA'),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='program_category',
            field=models.CharField(choices=[('P1', 'PROGRAM PEMBANGUNAN MURID/GURU'), ('P2', 'PROGRAM PENCERAPAN'), ('P3', 'PROGRAM KHAS'), ('P4', 'PROGRAM KEBANGSAAN'), ('P5', 'PROGRAM ANTARABANGSA'), ('P6', 'PROGRAM/RAKAN KERJASAMA'), ('P7', 'PROGRAM JANGKAUAN (6 ZON)'), ('P8', 'SEMINAR, CERAMAH, PLANETARIUM TALKS'), ('P9', 'LAIN-LAIN'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
