# Generated by Django 2.2.6 on 2020-10-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201013_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogram',
            name='description',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='max_participant',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='min_participant',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
