# Generated by Django 2.2.6 on 2020-10-20 03:10

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20201020_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgramImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('program_image', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('program'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_program_image_program_id', to='events.EducationalProgram')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
