# Generated by Django 2.2.6 on 2020-10-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_educationalprogramimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogram',
            name='video_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='website_link',
            field=models.URLField(blank=True),
        ),
    ]
