# Generated by Django 2.2.6 on 2020-10-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20201020_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
