# Generated by Django 2.2.6 on 2020-10-20 09:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0013_educationalprogramapplication_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='program_subcategory',
            field=models.CharField(choices=[('NSC', 'National Space Challenge'), ('KRK', 'Kejohanan Roket Kebangsaan'), ('NAV', 'Not Available')], default='NAV', max_length=3),
        ),
        migrations.CreateModel(
            name='EducationalProgramForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(blank=True, max_length=100)),
                ('teacher_school_name', models.CharField(blank=True, max_length=100)),
                ('teacher_school_address', models.CharField(blank=True, max_length=255)),
                ('teacher_school_postcode', models.CharField(blank=True, max_length=5)),
                ('teacher_school_division', models.CharField(blank=True, max_length=100)),
                ('teacher_school_state', models.CharField(blank=True, max_length=100)),
                ('teacher_tel', models.CharField(blank=True, max_length=20)),
                ('teacher_hp', models.CharField(blank=True, max_length=20)),
                ('teacher_email', models.CharField(blank=True, max_length=100)),
                ('teacher_fax', models.CharField(blank=True, max_length=20)),
                ('teacher_dob', models.DateField(blank=True, default=datetime.datetime.today)),
                ('teacher_age', models.IntegerField(default=0, null=True)),
                ('teacher_religion', models.CharField(choices=[('IS', 'Islam'), ('HD', 'Hindu'), ('BD', 'Buddha'), ('CT', 'Christian'), ('OT', 'Other')], default='OT', max_length=2)),
                ('teacher_gender', models.CharField(choices=[('FM', 'Female'), ('ML', 'Male'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('teacher_citizenship', models.CharField(choices=[('CZ', 'Citizen'), ('NC', 'Non Citizen'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('teacher_nric_passportno', models.CharField(blank=True, max_length=50)),
                ('teacher_maritalstatus', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('O', 'Other')], default='O', max_length=1)),
                ('teacher_tshirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL')], default='S', max_length=3)),
                ('teacher_contactperson_name', models.CharField(blank=True, max_length=100)),
                ('teacher_contactperson_tel', models.CharField(blank=True, max_length=20)),
                ('teacher_anysickness', models.CharField(blank=True, max_length=255)),
                ('teacher_anyallergies', models.CharField(blank=True, max_length=255)),
                ('teacher_vegetarian', models.BooleanField(default=False)),
                ('student_1_name', models.CharField(blank=True, max_length=100)),
                ('student_1_dob', models.DateField(blank=True, default=datetime.datetime.today)),
                ('student_1_age', models.IntegerField(default=0, null=True)),
                ('student_1_year', models.IntegerField(default=0, null=True)),
                ('student_1_religion', models.CharField(choices=[('IS', 'Islam'), ('HD', 'Hindu'), ('BD', 'Buddha'), ('CT', 'Christian'), ('OT', 'Other')], default='OT', max_length=2)),
                ('student_1_gender', models.CharField(choices=[('FM', 'Female'), ('ML', 'Male'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('student_1_citizenship', models.CharField(choices=[('CZ', 'Citizen'), ('NC', 'Non Citizen'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('student_1_nric_passportno', models.CharField(blank=True, max_length=50)),
                ('student_1_tshirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL')], default='S', max_length=3)),
                ('student_1_contactperson_name', models.CharField(blank=True, max_length=100)),
                ('student_1_contactperson_tel', models.CharField(blank=True, max_length=20)),
                ('student_1_anysickness', models.CharField(blank=True, max_length=255)),
                ('student_1_anyallergies', models.CharField(blank=True, max_length=255)),
                ('student_1_vegetarian', models.BooleanField(default=False)),
                ('student_2_name', models.CharField(blank=True, max_length=100)),
                ('student_2_dob', models.DateField(blank=True, default=datetime.datetime.today)),
                ('student_2_age', models.IntegerField(default=0, null=True)),
                ('student_2_year', models.IntegerField(default=0, null=True)),
                ('student_2_religion', models.CharField(choices=[('IS', 'Islam'), ('HD', 'Hindu'), ('BD', 'Buddha'), ('CT', 'Christian'), ('OT', 'Other')], default='OT', max_length=2)),
                ('student_2_gender', models.CharField(choices=[('FM', 'Female'), ('ML', 'Male'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('student_2_citizenship', models.CharField(choices=[('CZ', 'Citizen'), ('NC', 'Non Citizen'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('student_2_nric_passportno', models.CharField(blank=True, max_length=50)),
                ('student_2_tshirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL')], default='S', max_length=3)),
                ('student_2_contactperson_name', models.CharField(blank=True, max_length=100)),
                ('student_2_contactperson_tel', models.CharField(blank=True, max_length=20)),
                ('student_2_anysickness', models.CharField(blank=True, max_length=255)),
                ('student_2_anyallergies', models.CharField(blank=True, max_length=255)),
                ('student_2_vegetarian', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('IP', 'In process'), ('RJ', 'Rejected')], default='IP', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_program_form_customuser', to=settings.AUTH_USER_MODEL)),
                ('educational_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_program_form_educational_program', to='events.EducationalProgram')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
