# Generated by Django 2.2.6 on 2020-10-21 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20201020_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='is_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EducationalProgramActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('program_activity', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_program_activity_program_id', to='events.EducationalProgram')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='activities',
            field=models.ManyToManyField(related_name='educational_program_activity', to='events.EducationalProgramActivity'),
        ),
    ]
