# Generated by Django 2.2.6 on 2020-10-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20201021_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalprogramapplication',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='educationalprogramapplication',
            name='is_activity',
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educational_program_app_activity', to='events.EducationalProgramActivity'),
        ),
    ]
