# Generated by Django 2.2.6 on 2020-10-24 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20201021_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitapplication',
            name='tour_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitapplication',
            name='pic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_pic', to=settings.AUTH_USER_MODEL),
        ),
    ]
