# Generated by Django 2.2.6 on 2020-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20201024_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='asset_id',
            field=models.ManyToManyField(blank=True, related_name='exhibit_asset', to='assets.Asset'),
        ),
    ]
