# Generated by Django 2.2.6 on 2020-10-24 17:13

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20201024_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitdetail',
            name='image_link',
        ),
        migrations.AlterField(
            model_name='exhibitdetail',
            name='exhibit_list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_detail_exhibit_list_id', to='events.ExhibitList'),
        ),
        migrations.CreateModel(
            name='ExhibitDetailImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exhibit_detail_image', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('image'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('exhibit_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_detail_image_exhibit_detail', to='events.ExhibitDetail')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
