# Generated by Django 2.2.6 on 2020-10-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20201024_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitdetail',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
