# Generated by Django 2.2.6 on 2020-10-27 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20201024_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogram',
            name='venue_id',
            field=models.ManyToManyField(blank=True, related_name='educational_program_venue', to='venues.Venue'),
        ),
        migrations.AlterField(
            model_name='exhibitdetail',
            name='venue_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_detail_venue', to='venues.Venue'),
        ),
    ]
