# Generated by Django 2.2.6 on 2020-11-05 06:28

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20201105_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='document_link',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('document')),
        ),
    ]
