# Generated by Django 2.2.6 on 2020-11-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_educationalprogramapplication_document_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='equipment',
            field=models.TextField(blank=True),
        ),
    ]
