# Generated by Django 2.2.6 on 2020-11-06 07:27

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_exhibit_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='attachment_link',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('attachment')),
        ),
    ]
