# Generated by Django 2.2.6 on 2020-11-07 02:44

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_educationalprogram_attachment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='image_link',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('image')),
        ),
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='video_link',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('video')),
        ),
    ]
