# Generated by Django 2.2.6 on 2020-11-07 03:48

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20201107_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=255)),
                ('description', models.TextField(default='NA')),
                ('status', models.BooleanField(default=False)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('image'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
