# Generated by Django 2.2.6 on 2020-11-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='program_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
