# Generated by Django 2.2.6 on 2020-11-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_educationalprogram_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='zone',
            field=models.CharField(choices=[('A', 'Alam Semesta'), ('B', 'Ruang Kanak-kanak'), ('C', 'Teknologi Satelit'), ('D', 'Misi Angkasa'), ('E', 'Sistem Solar'), ('F', 'Gelombang'), ('G', 'Balai Cerap'), ('H', 'Menara Pemandangan'), ('N', 'Not Available')], default='N', max_length=1, unique=True),
        ),
    ]
