# Generated by Django 2.2.6 on 2020-11-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20201110_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogram',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
