# Generated by Django 2.2.6 on 2020-12-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20201116_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitlist',
            options={'ordering': ['name_ms']},
        ),
        migrations.RenameField(
            model_name='exhibitlist',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='exhibitlist',
            name='name_ms',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
