# Generated by Django 2.2.6 on 2020-12-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20201228_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitdetail',
            options={'ordering': ['name_ms']},
        ),
        migrations.RenameField(
            model_name='exhibitdetail',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='exhibitdetail',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='exhibitdetail',
            name='description_ms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibitdetail',
            name='name_ms',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
