# Generated by Django 2.2.6 on 2020-12-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20201228_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalprogram',
            options={'ordering': ['title_ms']},
        ),
        migrations.RenameField(
            model_name='educationalprogram',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='educationalprogram',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='description_ms',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='title_ms',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
