# Generated by Django 2.2.6 on 2020-12-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20201228_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalprogram',
            old_name='program_opento',
            new_name='program_opento_en',
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='program_opento_ms',
            field=models.CharField(default='', max_length=100),
        ),
    ]
