# Generated by Django 2.2.6 on 2021-05-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20201228_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='educationalprogramapplication',
            name='rejected_date',
            field=models.DateTimeField(null=True),
        ),
    ]
