# Generated by Django 2.2.6 on 2021-05-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_auto_20210504_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogramform',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='educationalprogramform',
            name='rejected_date',
            field=models.DateTimeField(null=True),
        ),
    ]
