# Generated by Django 2.2.6 on 2021-04-05 03:39

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOperatingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('report_by_position', models.CharField(blank=True, max_length=255)),
                ('operations_manager', models.CharField(blank=True, max_length=255)),
                ('technical_officer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('ticket_counter_clerk', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('stage_officer', models.CharField(blank=True, max_length=255)),
                ('info_counter_clerk', models.CharField(blank=True, max_length=255)),
                ('librarian', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('report_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitorSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_summary_show', models.IntegerField(default=0, null=True)),
                ('visitor_summary_space_pod', models.IntegerField(default=0, null=True)),
                ('visitor_summary_exhibition', models.IntegerField(default=0, null=True)),
                ('visitor_summary_kutubkhanah', models.IntegerField(default=0, null=True)),
                ('visitor_summary_all', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('daily_operating_report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_summary_daily_operating_report_id', to='dailyoperatingreports.DailyOperatingReport')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, choices=[('1000', '1000'), ('1100', '1100'), ('1200', '1200'), ('1300', '1300'), ('1400', '1400'), ('1500', '1500'), ('1600', '1600')], max_length=4)),
                ('show_name', models.CharField(blank=True, max_length=255)),
                ('show_audience', models.CharField(blank=True, max_length=20)),
                ('space_pod_participant', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('daily_operating_report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operating_schedule_daily_operating_report_id', to='dailyoperatingreports.DailyOperatingReport')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DetailReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('daily_operating_report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_report_daily_operating_report_id', to='dailyoperatingreports.DailyOperatingReport')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('M & E', 'M & E'), ('Safety', 'Keselamatan'), ('Cleaning', 'Kebersihan'), ('Landscape', 'Landskap'), ('NA', 'Tiada')], default='NA', max_length=20)),
                ('contractor_name', models.CharField(blank=True, max_length=255)),
                ('officer_name', models.CharField(blank=True, max_length=255)),
                ('attendance', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('daily_operating_report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_daily_operating_report_id', to='dailyoperatingreports.DailyOperatingReport')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
