# Generated by Django 2.2.6 on 2020-12-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisinterestings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatisinteresting',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='whatisinteresting',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='whatisinteresting',
            name='description_ms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='whatisinteresting',
            name='title_ms',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
    ]
