# Generated by Django 2.2.6 on 2020-12-09 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='NA', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('about-us', 'Mengenai Kami'), ('mission-vision', 'Visi & Misi'), ('noc', 'Maklumat NOC'), ('not-available', 'Tiada')], default='not-available', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
