# Generated by Django 2.2.6 on 2021-02-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamiccontents', '0003_auto_20210217_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccontent',
            name='category',
            field=models.CharField(choices=[('about-us', 'Mengenai Kami'), ('mission-vision', 'Visi & Misi'), ('noc', 'Maklumat NOC'), ('cio', 'Maklumat CIO'), ('organization-chart', 'Carta Organisasi'), ('charter', 'Piagam Pelanggan'), ('operating-hour', 'Waktu Operasi & Harga'), ('not-available', 'Tiada')], default='not-available', max_length=20),
        ),
    ]
