# Generated by Django 2.2.6 on 2021-03-04 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('VR', 'Verify Recaptcha'), ('SD', 'Statcounter - Summary Stats - Daily'), ('SY', 'Statcounter - Sumaary Stats - Yearly'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
