# Generated by Django 2.2.6 on 2021-04-19 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('total_in', models.IntegerField(default=0, null=True)),
                ('total_out', models.IntegerField(default=0, null=True)),
                ('total_stay', models.IntegerField(default=0, null=True)),
                ('date', models.DateField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('VR', 'Verify Recaptcha'), ('SD', 'Statcounter - Summary Stats - Daily'), ('SY', 'Statcounter - Sumaary Stats - Yearly'), ('PH', 'Head Counter - Post'), ('GH', 'Head Counter - Get'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
